language: node_js
node_js:
- 0.12.2
cache:
  directories:
  - node_modules
install: npm install
before_script:
- sleep 10
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
env:
  global:
  - NODE_ENV: test
  - URL: postgres://postgres:@127.0.0.1/nflstats_test
  - secure: